import path from 'path';
import fs from 'fs';
import { generateTimestamp } from '../utils/crypto';

export const updateContext = (vibeforgeDir: string) => {
  const docsDir = path.join(vibeforgeDir, 'docs');
  const memoryDir = path.join(vibeforgeDir, 'memory');
  const recordsDir = path.join(vibeforgeDir, 'records');
  const plansDir = path.join(vibeforgeDir, 'plans');
  const contextPath = path.join(vibeforgeDir, 'context.md');
  const promptPath = path.join(vibeforgeDir, 'prompt.txt');

  let contextContent = `# Project Context

**Generated by VibeForge**  
**Date:** ${generateTimestamp()}

---

`;

  if (fs.existsSync(promptPath)) {
    const promptContent = fs.readFileSync(promptPath, 'utf-8');
    if (promptContent.trim()) {
      contextContent += `## Prompt\n\n${promptContent}\n\n---\n\n`;
    }
  }

  const readDirectory = (dir: string, header: string) => {
    if (fs.existsSync(dir)) {
      const items = fs
        .readdirSync(dir, { withFileTypes: true })
        .sort((a, b) => a.name.localeCompare(b.name));
      if (items.length > 0) {
        contextContent += `## ${header}\n\n`;
        items.forEach((item) => {
          if (item.isFile()) {
            const filePath = path.join(dir, item.name);
            const content = fs.readFileSync(filePath, 'utf-8');
            contextContent += `### ${item.name}\n\n${content}\n\n---\n\n`;
          } else if (item.isDirectory()) {
            contextContent += `### 📁 ${item.name}\n\n`;
            const recordMetaPath = path.join(dir, item.name, 'meta.json');
            if (fs.existsSync(recordMetaPath)) {
              const meta = JSON.parse(fs.readFileSync(recordMetaPath, 'utf-8'));
              contextContent += `- **ID:** ${meta.id}\n`;
              contextContent += `- **Timestamp:** ${meta.timestamp}\n`;
              contextContent += `- **Target:** ${meta.targetPath}\n`;
            }
            contextContent += '\n---\n\n';
          }
        });
      }
    }
  };

  readDirectory(docsDir, 'Documentation');
  readDirectory(memoryDir, 'Memory');
  readDirectory(recordsDir, 'Records');
  readDirectory(plansDir, 'Plans');

  fs.writeFileSync(contextPath, contextContent);
  console.log('✅ Context updated!');
};
