import path from 'path';
import fs from 'fs';
import { estimateTokens, generateTimestamp } from '../utils/crypto';
import { loadConfig } from '../utils/fs';

interface ContextStats {
  docs: number;
  memory: number;
  records: number;
  plans: number;
  characters: number;
  estimatedTokens: number;
}

interface ContextBuildResult {
  contextPath: string;
  content: string;
  stats: ContextStats;
}

interface ContextOptions {
  silent?: boolean;
}

const MAX_SECTION_CHARS = 4000;
const MAX_RECORD_CHARS = 2500;

const clipContent = (content: string, maxLength: number): string => {
  const trimmed = content.trim();
  if (!trimmed) {
    return '';
  }

  if (trimmed.length <= maxLength) {
    return trimmed;
  }

  return `${trimmed.slice(0, maxLength)}\n...[truncated]`;
};

const byName = (left: fs.Dirent, right: fs.Dirent): number => left.name.localeCompare(right.name);

const byMostRecent =
  (dir: string) =>
  (left: fs.Dirent, right: fs.Dirent): number => {
    const leftTime = fs.statSync(path.join(dir, left.name)).mtimeMs;
    const rightTime = fs.statSync(path.join(dir, right.name)).mtimeMs;
    return rightTime - leftTime;
  };

const renderFileEntries = (
  dir: string,
  items: fs.Dirent[],
  maxLength: number
): { count: number; body: string } => {
  const entries = items
    .filter((item) => item.isFile())
    .map((item) => {
      const filePath = path.join(dir, item.name);
      const content = clipContent(fs.readFileSync(filePath, 'utf-8'), maxLength);
      if (!content) {
        return '';
      }

      return `### ${item.name}\n\n${content}`;
    })
    .filter(Boolean);

  return {
    count: entries.length,
    body: entries.join('\n\n---\n\n'),
  };
};

const renderRecordEntries = (recordsDir: string): { count: number; body: string } => {
  if (!fs.existsSync(recordsDir)) {
    return { count: 0, body: '' };
  }

  const items = fs.readdirSync(recordsDir, { withFileTypes: true }).sort(byMostRecent(recordsDir));
  const entries = items
    .map((item) => {
      const fullPath = path.join(recordsDir, item.name);

      if (item.isFile()) {
        const content = clipContent(fs.readFileSync(fullPath, 'utf-8'), MAX_RECORD_CHARS);
        return content ? `### ${item.name}\n\n${content}` : '';
      }

      const summaryPath = path.join(fullPath, 'summary.md');
      const metaPath = path.join(fullPath, 'meta.json');
      const summary = fs.existsSync(summaryPath)
        ? clipContent(fs.readFileSync(summaryPath, 'utf-8'), MAX_RECORD_CHARS)
        : '';
      const meta = fs.existsSync(metaPath)
        ? clipContent(fs.readFileSync(metaPath, 'utf-8'), 1200)
        : '';
      const content = [summary, meta].filter(Boolean).join('\n\n');

      return content ? `### ${item.name}\n\n${content}` : '';
    })
    .filter(Boolean);

  return {
    count: entries.length,
    body: entries.join('\n\n---\n\n'),
  };
};

export const updateContext = (
  vibeforgeDir: string,
  options: ContextOptions = {}
): ContextBuildResult => {
  const config = loadConfig();
  const docsDir = path.join(vibeforgeDir, 'docs');
  const memoryDir = path.join(vibeforgeDir, 'memory');
  const recordsDir = path.join(vibeforgeDir, 'records');
  const plansDir = path.join(vibeforgeDir, 'plans');
  const contextPath = path.join(vibeforgeDir, 'context.md');
  const promptPath = path.join(vibeforgeDir, 'prompt.txt');

  const docsEntries = fs.existsSync(docsDir)
    ? renderFileEntries(
        docsDir,
        fs.readdirSync(docsDir, { withFileTypes: true }).sort(byName),
        MAX_SECTION_CHARS
      )
    : { count: 0, body: '' };
  const memoryEntries = fs.existsSync(memoryDir)
    ? renderFileEntries(
        memoryDir,
        fs.readdirSync(memoryDir, { withFileTypes: true }).sort(byMostRecent(memoryDir)),
        2500
      )
    : { count: 0, body: '' };
  const planEntries = fs.existsSync(plansDir)
    ? renderFileEntries(
        plansDir,
        fs.readdirSync(plansDir, { withFileTypes: true }).sort(byMostRecent(plansDir)),
        2500
      )
    : { count: 0, body: '' };
  const recordEntries = renderRecordEntries(recordsDir);

  const promptContent = fs.existsSync(promptPath)
    ? fs.readFileSync(promptPath, 'utf-8').trim()
    : '';

  const sections = [
    `# Project Context

**Generated by VibeForge**  
**Date:** ${generateTimestamp()}  
**Workspace:** \`${process.cwd()}\`

---

## Project Info

${config.projectName ? `**Project Name:** ${config.projectName}` : ''}
${config.description ? `**Description:** ${config.description}` : ''}
${config.importantDocs && config.importantDocs.length > 0 ? `**Important Docs:** ${config.importantDocs.join(', ')}` : ''}
${config.ignore && config.ignore.length > 0 ? `**Ignored Paths:** ${config.ignore.join(', ')}` : ''}

---

## Workspace Summary

- Documentation files: ${docsEntries.count}
- Memory entries: ${memoryEntries.count}
- Records: ${recordEntries.count}
- Plans: ${planEntries.count}`,
  ];

  if (promptContent) {
    sections.push(`## Prompt\n\n${clipContent(promptContent, 2000)}`);
  }

  sections.push(
    docsEntries.body
      ? `## Architecture\n\n${docsEntries.body}`
      : '## Architecture\n\nNo project documentation has been added yet.',
    memoryEntries.body
      ? `## Recent Changes\n\n${memoryEntries.body}`
      : '## Recent Changes\n\nNo recent memory entries were found.',
    planEntries.body
      ? `## Active Plans\n\n${planEntries.body}`
      : '## Active Plans\n\nNo active plans were found.',
    recordEntries.body
      ? `## Records\n\n${recordEntries.body}`
      : '## Records\n\nNo records have been generated yet.'
  );

  const contextContent = sections.join('\n\n---\n\n') + '\n';
  const stats: ContextStats = {
    docs: docsEntries.count,
    memory: memoryEntries.count,
    records: recordEntries.count,
    plans: planEntries.count,
    characters: contextContent.length,
    estimatedTokens: estimateTokens(contextContent),
  };

  fs.writeFileSync(contextPath, contextContent);

  if (!options.silent) {
    console.log(`✅ Context updated: ${contextPath}`);
    console.log(
      `   Docs: ${stats.docs} | Memory: ${stats.memory} | Records: ${stats.records} | Plans: ${stats.plans} | Tokens: ~${stats.estimatedTokens}`
    );
  }

  return {
    contextPath,
    content: contextContent,
    stats,
  };
};
