import path from 'path';
import fs from 'fs';
import { generateTimestamp } from '../utils/crypto';
import { generateAgentMd } from '../services/agent';
import { updateContext } from '../services/context';

const COMMON_DOCS = ['PRD.md', 'RULES.txt', 'TECH_DOC.md', 'AGENT.md'];

export const initCommand = (options: any) => {
  const vibeforgeDir = path.join(process.cwd(), '.vibeforge');
  const dirs = [
    path.join(vibeforgeDir, 'memory'),
    path.join(vibeforgeDir, 'records'),
    path.join(vibeforgeDir, 'docs'),
    path.join(vibeforgeDir, 'plans'),
  ];

  if (!fs.existsSync(vibeforgeDir)) {
    dirs.forEach((dir) => {
      fs.mkdirSync(dir, { recursive: true });
    });

    const contextPath = path.join(vibeforgeDir, 'context.md');
    if (!fs.existsSync(contextPath)) {
      fs.writeFileSync(
        contextPath,
        `# Project Context

**Generated by VibeForge**  
**Date:** ${generateTimestamp()}

---

`
      );
    }

    const promptPath = path.join(vibeforgeDir, 'prompt.txt');
    if (!fs.existsSync(promptPath)) {
      fs.writeFileSync(promptPath, '');
    }

    console.log('🎉 VibeForge workspace initialized!');

    if (options.include) {
      const docsDir = path.join(vibeforgeDir, 'docs');
      let includedCount = 0;
      COMMON_DOCS.forEach((doc) => {
        const sourcePath = path.join(process.cwd(), doc);
        if (fs.existsSync(sourcePath)) {
          const destPath = path.join(docsDir, doc);
          fs.copyFileSync(sourcePath, destPath);
          console.log(`  📄 Included: ${doc}`);
          includedCount++;
        }
      });

      if (includedCount > 0) {
        generateAgentMd(vibeforgeDir);
        updateContext(vibeforgeDir);
      }
    }
  } else {
    console.log('ℹ️  VibeForge workspace already exists.');
  }
};
