import path from 'path';
import fs from 'fs';
import { generateTimestamp } from '../utils/crypto';
import { generateAgentMd } from '../services/agent';
import { updateContext } from '../services/context';
import { loadConfig } from '../utils/fs';

const COMMON_DOCS = ['PRD.md', 'RULES.txt', 'TECH_DOC.md'];

const ensureDir = (dir: string): boolean => {
  if (fs.existsSync(dir)) {
    return false;
  }

  fs.mkdirSync(dir, { recursive: true });
  return true;
};

const ensureFile = (filePath: string, contents: string): boolean => {
  if (fs.existsSync(filePath)) {
    return false;
  }

  fs.writeFileSync(filePath, contents);
  return true;
};

export const initCommand = (options: any) => {
  const vibeforgeDir = path.join(process.cwd(), '.vibeforge');
  const configPath = path.join(process.cwd(), 'vibeforge.json');
  const dirs = [
    path.join(vibeforgeDir, 'memory'),
    path.join(vibeforgeDir, 'records'),
    path.join(vibeforgeDir, 'docs'),
    path.join(vibeforgeDir, 'plans'),
  ];

  const createdRoot = ensureDir(vibeforgeDir);
  const createdDirs = dirs.filter((dir) => ensureDir(dir));
  const contextPath = path.join(vibeforgeDir, 'context.md');
  const promptPath = path.join(vibeforgeDir, 'prompt.txt');
  const defaultConfig = JSON.stringify(
    {
      projectName: '',
      description: '',
      importantDocs: [],
      ignore: [],
      ai: {
        aiProvider: '',
        openRouterApiKey: '',
        openRouterModel: '',
        openRouterFallbackModel: '',
        openAiApiKey: '',
        openAiModel: '',
        localModelUrl: '',
        localModelName: '',
        openRouterHttpReferer: '',
        openRouterXTitle: '',
      },
    },
    null,
    2
  );
  const createdFiles = [
    ensureFile(
      contextPath,
      `# Project Context

**Generated by VibeForge**  
**Date:** ${generateTimestamp()}

---
`
    )
      ? 'context.md'
      : '',
    ensureFile(promptPath, '') ? 'prompt.txt' : '',
    ensureFile(configPath, defaultConfig) ? 'vibeforge.json' : '',
  ].filter(Boolean);

  generateAgentMd(vibeforgeDir);

  let includedCount = 0;
  let skippedCount = 0;
  if (options.include) {
    const docsDir = path.join(vibeforgeDir, 'docs');
    COMMON_DOCS.forEach((doc) => {
      const sourcePath = path.join(process.cwd(), doc);
      if (!fs.existsSync(sourcePath)) {
        return;
      }

      const destPath = path.join(docsDir, doc);
      fs.copyFileSync(sourcePath, destPath);
      includedCount++;
    });

    skippedCount = COMMON_DOCS.length - includedCount;
  }

  const contextResult = updateContext(vibeforgeDir, { silent: true });

  console.log(
    `\n${createdRoot ? '🎉 VibeForge workspace initialized!' : '🛠️ VibeForge workspace repaired and refreshed!'}`
  );
  console.log(`   Workspace: ${vibeforgeDir}`);
  console.log(`   New folders: ${createdDirs.length} | New files: ${createdFiles.length}`);
  console.log(
    `   Context tokens: ~${contextResult.stats.estimatedTokens} | Docs: ${contextResult.stats.docs} | Memory: ${contextResult.stats.memory} | Records: ${contextResult.stats.records}`
  );

  if (options.include) {
    console.log(
      `   Included docs: ${includedCount}${skippedCount > 0 ? ` | Missing in repo root: ${skippedCount}` : ''}`
    );
  }

  console.log('\nNext steps:');
  console.log('  1. vibeforge sync');
  console.log('  2. vibeforge ask "What should I build next?"');
  console.log('  3. vibeforge dashboard');
  console.log('');
};
